
version: "3.5"

services:

  dev:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/bankmapper/

    command: bash -c "python application.py"
